In [2]:
import Pkg; Pkg.add("FFTW")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.11/Project.toml`
  No Changes to `~/.julia/environments/v1.11/Manifest.toml`


In [3]:
# setting the N value

N = 5;

# points in t direction
# trigpts returns N equally spaced points on an interval -1 to 1
# range is kind of like linspace! the length

t = pi* range(-1,1, length=N+1)[1:end-1];
t = reshape(t,:,1)


# chebpts returns chebyshev points of the second kind
# generates N+1 cheb pts in the interval [-1, 1], so includes endpoints
# points are clustered near the endpoints

r = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];
z = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];


# going from N-1 to 0 ensures that endpoints are included bc when you 
#plug in (N-1) and 0 into the formula, you get the endpoints included -1 and 1 regardless of N
# cosine part is just a formula for cheb pts of second kind

display(t)
display(z)
display(r)

5×1 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 5, 1) with eltype Float64:
 -3.141592653589793
 -1.8849555921538759
 -0.6283185307179586
  0.6283185307179586
  1.8849555921538759

5-element Vector{Float64}:
 -1.0
 -0.7071067811865475
  6.123233995736766e-17
  0.7071067811865476
  1.0

5-element Vector{Float64}:
 -1.0
 -0.7071067811865475
  6.123233995736766e-17
  0.7071067811865476
  1.0

In [4]:
# now to make the grid! this was a bit incorrect because we need the different layers? 
#I found a package that works better!

# tt = 
rr = hcat([r for _ in 1:N]...)
zz = vcat([transpose(z) for _ in 1:N]...)
 
display(rr)
display(zz)

5×5 Matrix{Float64}:
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

5×5 Matrix{Float64}:
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

In [5]:
# same row vector vertical stacked
rr = [ri for ri in r, zi in z, ti in t]

# same column vector horizontal stacked
zz = [zi for ri in r, zi in z, ti in t]

# every entry in a matrix the same, but each layer has different value
tt = [ti for ri in r, zi in z, ti in t]

rr = dropdims(rr; dims=4)
tt = dropdims(tt; dims=4)
zz = dropdims(zz; dims=4)

display(rr)
display(zz)
display(tt)


5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

[:, :, 2] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

[:, :, 3] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0          

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 2] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 3] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 4] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 5] =
 -1.0  -0.7

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159

[:, :, 2] =
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496

[:, :, 3] =
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319

[:, :, 4] =
 0.628319  0.628319  0.628319  0.628319  0.628319
 0.628319  0.628319  0.628319  0.628319  0.628319
 0.628319  0.628319  0.628319  0.628319  0.628319

In [6]:
# get the matrices we want: C02, D2, A, coF
using LinearAlgebra, SparseArrays

# C01: Convert Chebyshev-T (T) coefficients to Chebyshev-U (U)
C01 = spdiagm(0 => 0.5*ones(N), 2 => -0.5*ones(N-2))
C01[1,1] = 1.0
println("C01:")
display(C01)
# C12: Convert Chebyshev-U to C^2, the continuous function space
K_1 = 1.0 ./ (1:N)
K_2 = 1.0 ./ (3:N)
C12 = spdiagm(0 => K_1, 2 => -K_2)
println("C12:")
display(C12)
# C02: Convert Chebyshev-T to C^2 (It's C01 * C12)
C02 = C01 * C12
println("C02:")
display(C02)

# D1: Differentiate Chebyshev-T and convert to Chebyshev-U
D1 = spdiagm(1 => 1:N-1)
println("D1: ")
display(D1)
# D2: Differentiate Chebyshev-T twice and convert to C²
D2 = spdiagm(2 => 2 .* (2:N-1))
println("D2: ")
display(D2)
# D0: Differentiate Chebyshev-T once
D0 = C01 \ D1
println("D0: ")
display(D0)

# R0: Multiply Cheb-T by x
R0 = spdiagm(-1 => 0.5*ones(N-1), 1 => 0.5*ones(N-1))
R0[2,1] = 1.0
println("R0:")
display(R0)
# R2: Multiply in C² space
denom = 4:2:2*N+2
K_sub  = ((1:N) ./ denom)[1:N-1]
K_super = ((3:N+2) ./ denom[1:N])[2:N]
R2 = spdiagm(-1 => K_sub, 1 => K_super)
println("R2:")
display(R2)
# R1: Multiply in Cheb-U basis
R1 = C12 \ R2 * C12
println("R1:")
display(R1)

# A: Laplacian operator
A = R2 * R2 * D2 + R2 * C12 * D1
println("A:")
display(A)

# coF: Laplacian multiplier
coF = R2 * R2 * C02
println("coF:")
display(coF)

C01:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 1.0   ⋅   -0.5    ⋅     ⋅ 
  ⋅   0.5    ⋅   -0.5    ⋅ 
  ⋅    ⋅    0.5    ⋅   -0.5
  ⋅    ⋅     ⋅    0.5    ⋅ 
  ⋅    ⋅     ⋅     ⋅    0.5

C12:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 1.0   ⋅   -0.333333    ⋅      ⋅ 
  ⋅   0.5    ⋅        -0.25    ⋅ 
  ⋅    ⋅    0.333333    ⋅    -0.2
  ⋅    ⋅     ⋅         0.25    ⋅ 
  ⋅    ⋅     ⋅          ⋅     0.2

C02:


5×5 SparseMatrixCSC{Float64, Int64} with 9 stored entries:
 1.0   ⋅    -0.5         ⋅      0.1
  ⋅   0.25    ⋅        -0.25     ⋅ 
  ⋅    ⋅     0.166667    ⋅     -0.2
  ⋅    ⋅      ⋅         0.125    ⋅ 
  ⋅    ⋅      ⋅          ⋅      0.1

D1: 


5×5 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  2  ⋅  ⋅
 ⋅  ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  ⋅  4
 ⋅  ⋅  ⋅  ⋅  ⋅

D2: 


5×5 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  ⋅  4  ⋅  ⋅
 ⋅  ⋅  ⋅  6  ⋅
 ⋅  ⋅  ⋅  ⋅  8
 ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅

D0: 


5×5 Matrix{Float64}:
 0.0  1.0  0.0  3.0  0.0
 0.0  0.0  4.0  0.0  8.0
 0.0  0.0  0.0  6.0  0.0
 0.0  0.0  0.0  0.0  8.0
 0.0  0.0  0.0  0.0  0.0

R0:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅   0.5   ⋅    ⋅    ⋅ 
 1.0   ⋅   0.5   ⋅    ⋅ 
  ⋅   0.5   ⋅   0.5   ⋅ 
  ⋅    ⋅   0.5   ⋅   0.5
  ⋅    ⋅    ⋅   0.5   ⋅ 

R2:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅    0.666667   ⋅      ⋅    ⋅ 
 0.25   ⋅        0.625   ⋅    ⋅ 
  ⋅    0.333333   ⋅     0.6   ⋅ 
  ⋅     ⋅        0.375   ⋅   0.583333
  ⋅     ⋅         ⋅     0.4   ⋅ 

R1:


5×5 Matrix{Float64}:
 0.0  0.5  0.0  0.0   0.0
 0.5  0.0  0.5  0.0  -0.166667
 0.0  0.5  0.0  0.5   0.0
 0.0  0.0  0.5  0.0   0.166667
 0.0  0.0  0.0  0.5   0.0

A:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅    ⋅    1.33333    ⋅     2.66667
  ⋅   0.25   ⋅        2.625   ⋅ 
  ⋅    ⋅    0.666667   ⋅     3.73333
  ⋅    ⋅     ⋅        1.125   ⋅ 
  ⋅    ⋅     ⋅         ⋅     1.6

coF:


5×5 SparseMatrixCSC{Float64, Int64} with 12 stored entries:
 0.166667    ⋅       -0.0138889    ⋅         -0.0666667
  ⋅         0.09375    ⋅         -0.046875     ⋅ 
 0.0833333   ⋅        0.0305556    ⋅         -0.0433333
  ⋅         0.03125    ⋅          0.0260417    ⋅ 
  ⋅          ⋅        0.025        ⋅         -0.00666667

In [7]:
# dummy test function
finit(r, z, θ, t) = r .* sin.(θ) .+ z .* cos.(θ)
finit_test(r,z,θ) = finit(r,z,θ,0)

# initialize CFS array to hold function values at t = 0
CFS = zeros(size(rr))

# Evaluate initial condition on the full (r, z, θ) grid
for j in 1:N
    CFS[:, j, :] = finit_test(rr[:,j,:],zz[:,j,:], tt[:,j,:])
end

display(CFS);

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 1.0  0.707107   6.12323e-17  -0.707107  -1.0
 1.0  0.707107   2.53633e-17  -0.707107  -1.0
 1.0  0.707107  -6.12323e-17  -0.707107  -1.0
 1.0  0.707107  -1.47828e-16  -0.707107  -1.0
 1.0  0.707107  -1.83697e-16  -0.707107  -1.0

[:, :, 2] =
  1.26007    1.16956    0.951057      0.732549   0.64204
  0.981516   0.891007   0.672499      0.45399    0.363482
  0.309017   0.218508  -7.71572e-17  -0.218508  -0.309017
 -0.363482  -0.45399   -0.672499     -0.891007  -0.981516
 -0.64204   -0.732549  -0.951057     -1.16956   -1.26007

[:, :, 3] =
 -0.221232   0.0157238   0.587785      1.15985    1.3968
 -0.39339   -0.156434    0.415627      0.987688   1.22464
 -0.809017  -0.572061    1.35465e-17   0.572061   0.809017
 -1.22464   -0.987688   -0.415627      0.156434   0.39339
 -1.3968    -1.15985    -0.587785     -0.0157238  0.221232

[:, :, 4] =
 -1.3968    -1.15985    -0.587785     -0.0157238  0.221232
 -1.22464   -0.987688   -0.415627      0.156434   0.3933

In [8]:
# replicate V2C_cyl function
using FFTW
using LinearAlgebra

function V2C_cyl(vals, a)
    # julia uses mapslices with dims=d, which works directly on a specific dimension so no need to manually reshape like in MATLAB

    dim = ndims(vals)
    sz = size(vals)
    # println(dim)
    # println(length(a))
    
    # check that length(a) = # of dimensions
    @assert length(a) == dim "Length of 'a' must match number of dimensions in vals."
    println("got here past assert")

    # loop through dims, deciding which transform to apply
    for d in 1:dim
        # if t, FFT along dim
        if a[d] == 't' || a[d] == 'T'
            vals = mapslices(x -> fft(x) / length(x), vals; dims=(1,2))
            println("t done")
        else
            if a[d] == 'r'
                vals = mapslices(x -> dct(x, 2), vals; dims=(2,3))
                println("r done")
            else a[d] == 'z'
                vals = mapslices(x -> dct(x, 2), vals; dims=(1,3))
                println("z done")
            end            
        end

        # julia uses mapslices, which works directly on a specific dimension so no need to reshape and permute dimensions like in MATLAB
    end

    return vals
end

V2C_cyl (generic function with 1 method)

In [9]:
T = 1
# display(CFS)
test = V2C_cyl(CFS,"rzt")
# CFS(:,:,:,2:T)=zeros
# println(CFS)

got here past assert
r done
z done
t done


5×5×5 Array{ComplexF64, 3}:
[:, :, 1] =
 -5.32907e-17+0.0im        …      0.224584+0.309114im
   -0.0473484+0.0651695im     -9.86005e-18+1.22097e-17im
   -0.0325482+0.0105756im     -1.32171e-17-8.97204e-18im
   -0.0325482-0.0105756im      1.47751e-17-1.60611e-17im
   -0.0473484-0.0651695im      2.55415e-17+4.37631e-18im

[:, :, 2] =
 -5.32907e-17+0.0im        …      0.137347+0.189043im
     0.189043-0.260195im       2.48122e-17+3.60733e-18im
     0.129951-0.0422238im      3.91544e-18+3.60733e-18im
     0.129951+0.0422238im     -3.91544e-18+3.60733e-18im
     0.189043+0.260195im       3.92987e-18+3.60733e-18im

[:, :, 3] =
       0.0+0.0im        …     -0.263789-0.363075im
  0.141038-0.194123im       3.65265e-17-1.26706e-17im
 0.0969525-0.0315018im      2.38536e-17-1.06854e-17im
 0.0969525+0.0315018im      6.46095e-18-8.20285e-18im
  0.141038+0.194123im      -1.09295e-17-1.26706e-17im

[:, :, 4] =
 3.55271e-17+0.0im        …     -0.222233-0.305877im
   -0.305877+0.421004im      -2.07297