# Imports

In [187]:
import Pkg; Pkg.add("FFTW")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.11/Project.toml`
  No Changes to `~/.julia/environments/v1.11/Manifest.toml`


# Setting up rr, zz, tt

In [75]:
# setting the N value

N = 5;
T = 1;

# points in t direction
# trigpts returns N equally spaced points on an interval -1 to 1
# range is kind of like linspace! the length

t = pi* range(-1,1, length=N+1)[1:end-1];
t = reshape(t,:,1)


# chebpts returns chebyshev points of the second kind
# generates N+1 cheb pts in the interval [-1, 1], so includes endpoints
# points are clustered near the endpoints

r = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];
z = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];


# going from N-1 to 0 ensures that endpoints are included bc when you 
#plug in (N-1) and 0 into the formula, you get the endpoints included -1 and 1 regardless of N
# cosine part is just a formula for cheb pts of second kind

display(t)
display(z)
display(r)

5×1 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 5, 1) with eltype Float64:
 -3.141592653589793
 -1.8849555921538759
 -0.6283185307179586
  0.6283185307179586
  1.8849555921538759

5-element Vector{Float64}:
 -1.0
 -0.7071067811865475
  6.123233995736766e-17
  0.7071067811865476
  1.0

5-element Vector{Float64}:
 -1.0
 -0.7071067811865475
  6.123233995736766e-17
  0.7071067811865476
  1.0

In [76]:
# now to make the grid! this was a bit incorrect because we need the different layers? 
#I found a package that works better!

# tt = 
rr = hcat([r for _ in 1:N]...)
zz = vcat([transpose(z) for _ in 1:N]...)
 
display(rr)
display(zz)

5×5 Matrix{Float64}:
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

5×5 Matrix{Float64}:
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

In [77]:
# same row vector vertical stacked
rr = [ri for ri in r, zi in z, ti in t]

# same column vector horizontal stacked
zz = [zi for ri in r, zi in z, ti in t]

# every entry in a matrix the same, but each layer has different value
tt = [ti for ri in r, zi in z, ti in t]

rr = dropdims(rr; dims=4)
tt = dropdims(tt; dims=4)
zz = dropdims(zz; dims=4)

display(rr)
display(zz)
display(tt)


5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

[:, :, 2] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

[:, :, 3] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0          

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 2] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 3] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 4] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 5] =
 -1.0  -0.7

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159

[:, :, 2] =
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496

[:, :, 3] =
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319

[:, :, 4] =
 0.628319  0.628319  0.628319  0.628319  0.628319
 0.628319  0.628319  0.628319  0.628319  0.628319
 0.628319  0.628319  0.628319  0.628319  0.628319

# Create Matrices

In [78]:
# get the matrices we want: C02, D2, A, coF
using LinearAlgebra, SparseArrays

# C01: Convert Chebyshev-T (T) coefficients to Chebyshev-U (U)
C01 = spdiagm(0 => 0.5*ones(N), 2 => -0.5*ones(N-2))
C01[1,1] = 1.0
println("C01:")
display(C01)
# C12: Convert Chebyshev-U to C^2, the continuous function space
K_1 = 1.0 ./ (1:N)
K_2 = 1.0 ./ (3:N)
C12 = spdiagm(0 => K_1, 2 => -K_2)
println("C12:")
display(C12)
# C02: Convert Chebyshev-T to C^2 (It's C01 * C12)
C02 = C01 * C12
println("C02:")
display(C02)

# D1: Differentiate Chebyshev-T and convert to Chebyshev-U
D1 = spdiagm(1 => 1:N-1)
println("D1: ")
display(D1)
# D2: Differentiate Chebyshev-T twice and convert to C²
D2 = spdiagm(2 => 2 .* (2:N-1))
println("D2: ")
display(D2)
# D0: Differentiate Chebyshev-T once
D0 = C01 \ D1
println("D0: ")
display(D0)

# R0: Multiply Cheb-T by x
R0 = spdiagm(-1 => 0.5*ones(N-1), 1 => 0.5*ones(N-1))
R0[2,1] = 1.0
println("R0:")
display(R0)
# R2: Multiply in C² space
denom = 4:2:2*N+2
K_sub  = ((1:N) ./ denom)[1:N-1]
K_super = ((3:N+2) ./ denom[1:N])[2:N]
R2 = spdiagm(-1 => K_sub, 1 => K_super)
println("R2:")
display(R2)
# R1: Multiply in Cheb-U basis
R1 = C12 \ R2 * C12
println("R1:")
display(R1)

# A: Laplacian operator
A = R2 * R2 * D2 + R2 * C12 * D1
println("A:")
display(A)

# coF: Laplacian multiplier
coF = R2 * R2 * C02
println("coF:")
display(coF)

C01:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 1.0   ⋅   -0.5    ⋅     ⋅ 
  ⋅   0.5    ⋅   -0.5    ⋅ 
  ⋅    ⋅    0.5    ⋅   -0.5
  ⋅    ⋅     ⋅    0.5    ⋅ 
  ⋅    ⋅     ⋅     ⋅    0.5

C12:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 1.0   ⋅   -0.333333    ⋅      ⋅ 
  ⋅   0.5    ⋅        -0.25    ⋅ 
  ⋅    ⋅    0.333333    ⋅    -0.2
  ⋅    ⋅     ⋅         0.25    ⋅ 
  ⋅    ⋅     ⋅          ⋅     0.2

C02:


5×5 SparseMatrixCSC{Float64, Int64} with 9 stored entries:
 1.0   ⋅    -0.5         ⋅      0.1
  ⋅   0.25    ⋅        -0.25     ⋅ 
  ⋅    ⋅     0.166667    ⋅     -0.2
  ⋅    ⋅      ⋅         0.125    ⋅ 
  ⋅    ⋅      ⋅          ⋅      0.1

D1: 


5×5 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  2  ⋅  ⋅
 ⋅  ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  ⋅  4
 ⋅  ⋅  ⋅  ⋅  ⋅

D2: 


5×5 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  ⋅  4  ⋅  ⋅
 ⋅  ⋅  ⋅  6  ⋅
 ⋅  ⋅  ⋅  ⋅  8
 ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅

D0: 


5×5 Matrix{Float64}:
 0.0  1.0  0.0  3.0  0.0
 0.0  0.0  4.0  0.0  8.0
 0.0  0.0  0.0  6.0  0.0
 0.0  0.0  0.0  0.0  8.0
 0.0  0.0  0.0  0.0  0.0

R0:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅   0.5   ⋅    ⋅    ⋅ 
 1.0   ⋅   0.5   ⋅    ⋅ 
  ⋅   0.5   ⋅   0.5   ⋅ 
  ⋅    ⋅   0.5   ⋅   0.5
  ⋅    ⋅    ⋅   0.5   ⋅ 

R2:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅    0.666667   ⋅      ⋅    ⋅ 
 0.25   ⋅        0.625   ⋅    ⋅ 
  ⋅    0.333333   ⋅     0.6   ⋅ 
  ⋅     ⋅        0.375   ⋅   0.583333
  ⋅     ⋅         ⋅     0.4   ⋅ 

R1:


5×5 Matrix{Float64}:
 0.0  0.5  0.0  0.0   0.0
 0.5  0.0  0.5  0.0  -0.166667
 0.0  0.5  0.0  0.5   0.0
 0.0  0.0  0.5  0.0   0.166667
 0.0  0.0  0.0  0.5   0.0

A:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅    ⋅    1.33333    ⋅     2.66667
  ⋅   0.25   ⋅        2.625   ⋅ 
  ⋅    ⋅    0.666667   ⋅     3.73333
  ⋅    ⋅     ⋅        1.125   ⋅ 
  ⋅    ⋅     ⋅         ⋅     1.6

coF:


5×5 SparseMatrixCSC{Float64, Int64} with 12 stored entries:
 0.166667    ⋅       -0.0138889    ⋅         -0.0666667
  ⋅         0.09375    ⋅         -0.046875     ⋅ 
 0.0833333   ⋅        0.0305556    ⋅         -0.0433333
  ⋅         0.03125    ⋅          0.0260417    ⋅ 
  ⋅          ⋅        0.025        ⋅         -0.00666667

# Set Initial Condition

In [108]:
# dummy test function
finit(r, z, θ, t) = r .* sin.(θ) .+ z .* cos.(θ)
finit_test(r,z,θ) = finit(r,z,θ,0)

# initialize CFS array to hold function values at t = 0
CFS = zeros(size(rr))

# Evaluate initial condition on the full (r, z, θ) grid
for j in 1:N
    CFS[:, j, :] = finit_test(rr[:,j,:],zz[:,j,:], tt[:,j,:])
end

display(CFS);

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 1.0  0.707107   6.12323e-17  -0.707107  -1.0
 1.0  0.707107   2.53633e-17  -0.707107  -1.0
 1.0  0.707107  -6.12323e-17  -0.707107  -1.0
 1.0  0.707107  -1.47828e-16  -0.707107  -1.0
 1.0  0.707107  -1.83697e-16  -0.707107  -1.0

[:, :, 2] =
  1.26007    1.16956    0.951057      0.732549   0.64204
  0.981516   0.891007   0.672499      0.45399    0.363482
  0.309017   0.218508  -7.71572e-17  -0.218508  -0.309017
 -0.363482  -0.45399   -0.672499     -0.891007  -0.981516
 -0.64204   -0.732549  -0.951057     -1.16956   -1.26007

[:, :, 3] =
 -0.221232   0.0157238   0.587785      1.15985    1.3968
 -0.39339   -0.156434    0.415627      0.987688   1.22464
 -0.809017  -0.572061    1.35465e-17   0.572061   0.809017
 -1.22464   -0.987688   -0.415627      0.156434   0.39339
 -1.3968    -1.15985    -0.587785     -0.0157238  0.221232

[:, :, 4] =
 -1.3968    -1.15985    -0.587785     -0.0157238  0.221232
 -1.22464   -0.987688   -0.415627      0.156434   0.3933

# chebtech2.vals2coeffs and trigtech.vals2coeffs in Julia 

In [89]:
# replicate chebtech2.vals2coeffs and trigtech.vals2coeffs function
using FFTW
using LinearAlgebra

function chebv2c(vals)
    N = size(vals, 1)
    coeffs = zeros(size(vals))

    for col = 1:size(vals, 2)
        v = vals[:, col] # single column vector
        v_backwards = v[end-1:-1:2] # backwards
        v_ext = vcat(v, v_backwards) # mirrored but not the first at the end, so like 1 2 3 2
        c_ext = real(fft(v_ext)) # fft but only take real part
        c = c_ext[1:N] / (N-1) # normalizes the first half, N = first half size
        c[1] = c[1] / 2
        c[end] = c[end] / 2
        coeffs[:, col] = c
    end

    return coeffs

end



function trigv2c(vals)
    N = size(vals, 1)

    coeffs = (1/N)*fftshift(fft(vals, 1), 1)
    # display("coeffs below")
    # display(size(coeffs))
    # display(coeffs)

    if ( mod(N, 2) != 0 ) # N is odd
        even_odd_fix = (-1).^(-(N-1)/2:(N-1)/2)
    else # N is even
        even_odd_fix = (-1).^((-N/2):(N/2-1))
    end

    # display("evenoddfix size")
    # display(size(even_odd_fix))
    # display(even_odd_fix)

    coeffs = coeffs .* even_odd_fix

    return coeffs
end


trigv2c (generic function with 1 method)

# Testing above implementations

In [22]:
# vals_cheb = [-1; -0.5; 0; 0.5; 1]
# display(vals_cheb)
# vals_cheb_updated = chebv2c(vals_cheb);
# display("vals_cheb updated")
# display(vals_cheb_updated)


# vals_trig = [-1 -0.5im 0 0.5im 1; -1im -0.5 0 0.5 1im; -1 -0.5 0im 0.5 1]
# display(vals_trig)
# vals_trig_updated = trigv2c(vals_trig)
# display("vals_trig updated")
# display(vals_trig_updated)

In [23]:
# T = 1
# display(CFS)
# CFS_after = V2C_cyl(CFS,"rzt")
# display(CFS_after);
# # CFS(:,:,:,2:T)=zeros
# # println(CFS)

In [24]:
# function V2C_cyl(vals, a)
#     # julia uses mapslices with dims=d, which works directly on a specific dimension so no need to manually reshape like in MATLAB

#     dim = ndims(vals)
#     sz = size(vals)
#     # println(dim)
#     # println(length(a))
    
#     # check that length(a) = # of dimensions
#     @assert length(a) == dim "Length of 'a' must match number of dimensions in vals."
#     #println("got here past assert")

#     # loop through dims, deciding which transform to apply
#     for d in 1:dim
#         # if t, FFT along dim
#         if a[d] == 't' || a[d] == 'T'
#             vals = mapslices(x -> fft(x) / length(x), vals; dims=(1,2))
#             #println("t done")
#         else
#             if a[d] == 'r'
#                 vals = mapslices(x -> dct(x, 2), vals; dims=(2,3))
#                 #println("r done")
#             else a[d] == 'z'
#                 vals = mapslices(x -> dct(x, 2), vals; dims=(1,3))
#                 #println("z done")
#             end            
#         end

#         # julia uses mapslices, which works directly on a specific dimension so no need to reshape and permute dimensions like in MATLAB
#     end

#     return vals
# end

# Running V2C_cyl

In [181]:
using Printf


function pretty_print_array_matlab_style(A::Array; digits=4)
    println()

    iscomplexarray = eltype(A) <: Complex

    for k in 1:size(A, 3)
        slice = A[:, :, k]
        abs_slice = iscomplexarray ? abs.(slice) : abs.(real.(slice))
        maxval = maximum(abs_slice)
        
        println("(:,:, $k) =\n")

        if maxval == 0.0
            scale = 0
            scaled = slice
        else
            scale = floor(Int, log10(maxval))
            scaled = slice / (10.0^scale)
        end

        use_scale = maxval < 1e-3 || maxval > 1e4

        if use_scale
            println(@sprintf("   1.0e%+d *\n", scale))
        end

        for i in 1:size(slice, 1)
            for j in 1:size(slice, 2)
                val = use_scale ? scaled[i, j] : slice[i, j]
                if iscomplexarray
                    re = @sprintf("%7.*f", digits, real(val))
                    im = @sprintf("%7.*f", digits, imag(val))
                    sign_str = startswith(im, "-") ? "" : "+"
                    print(" $re $sign_str $im" * "i  ")
                else
                    print(@sprintf("%8.*f  ", digits, val))
                end
            end
            println()
        end
        println()
    end
end

pretty_print_array_matlab_style (generic function with 1 method)

In [ ]:
function V2C_cyl(vals, a)
    dim = length(a)
    SIZE = size(vals)

    a = collect(lowercase(a))

    for kk in 1:dim
        # first, "vectorize" to catch all columns at once.
        vals = reshape(vals, SIZE[kk], div(length(vals), SIZE[kk]))

        # apply the appropriate transform
        if a[kk] == 't'
            vals = trigv2c(vals)
        elseif a[kk] == '0'
            # do nothing
        else
            vals = chebv2c(vals)
        end

        # Reshape and permute back
        if dim != 1
            vals = reshape(vals, (5, 5, 5))
            vals = permutedims(vals, (2, 3, 1))
        end

        if a[kk] == 'r' || a[kk] == 'z'
            vals[:,:,2] .= -vals[:,:,2]
            vals[:,:,4] .= -vals[:,:,4]
        end
        
        println("dimension ", a[kk])
        pretty_print_array_matlab_style(vals)
        
    end

    return vals

end


V2C_cyl (generic function with 1 method)

In [186]:
CFS_func = V2C_cyl(CFS, "rzt")
pretty_print_array_matlab_style(CFS_func)
CFS_func[:,:,:,2:T] .= 0.0
display(CFS_func);

dimension r

(:,:, 1) =

  1.0000    0.3090   -0.8090   -0.8090    0.3090  
  0.7071    0.2185   -0.5721   -0.5721    0.2185  
 -0.0000   -0.0000    0.0000    0.0000    0.0000  
 -0.7071   -0.2185    0.5721    0.5721   -0.2185  
 -1.0000   -0.3090    0.8090    0.8090   -0.3090  

(:,:, 2) =

 -0.0000   -0.9511   -0.5878    0.5878    0.9511  
 -0.0000   -0.9511   -0.5878    0.5878    0.9511  
 -0.0000   -0.9511   -0.5878    0.5878    0.9511  
 -0.0000   -0.9511   -0.5878    0.5878    0.9511  
 -0.0000   -0.9511   -0.5878    0.5878    0.9511  

(:,:, 3) =

   1.0e-17 *

  0.0000    5.5511    0.0000    0.0000    0.0000  
  0.0000    5.5511    0.0000    0.0000    0.0000  
  0.0000    3.8579   -0.6773   -4.2765   -1.9657  
  0.0000    1.3878    5.5511    5.5511   -4.1633  
  0.0000    0.0000    0.0000    0.0000   -5.5511  

(:,:, 4) =

   1.0e-17 *

 -4.4014   -5.5511    5.5511   -5.5511    5.5511  
  2.2993    5.5511    5.5511   -0.0000    5.5511  
 -0.0000   -5.5511   -0.0000   -0.0000   

5×5×5 Array{ComplexF64, 3}:
[:, :, 1] =
  9.94659e-19-6.02159e-18im  …   -3.8717e-18+2.13557e-18im
 -2.56508e-17-8.63296e-18im      1.15239e-18+0.0im
 -9.38156e-19+4.8943e-18im      -2.12346e-18-1.63143e-18im
 -3.53463e-18-1.77077e-17im     -8.66816e-19-5.90258e-18im
 -6.22375e-19+1.94301e-18im      4.37794e-19+3.11576e-19im

[:, :, 2] =
 3.03989e-17+1.46079e-17im  …  -1.74886e-17+1.40937e-18im
 2.56508e-17+0.5im             -1.15239e-18-0.0im
 1.76589e-18-1.17462e-17im     -6.35831e-18-1.18731e-18im
 4.31458e-19+1.0944e-17im       3.96998e-18+3.64799e-18im
 2.53589e-18-4.18163e-18im     -4.73062e-18-1.54192e-18im

[:, :, 3] =
  1.57449e-17+0.0im   4.44089e-17+0.0im  …  -1.47862e-17+0.0im
 -2.56508e-17+0.0im          -0.0+0.0im      1.15239e-18+0.0im
  5.40809e-18+0.0im   -3.5885e-18+0.0im      -8.4697e-18+0.0im
   8.4253e-18+0.0im  -1.17757e-17+0.0im     -1.28267e-17+0.0im
  6.31652e-18+0.0im    5.0749e-18+0.0im     -1.03368e-17+0.0im

[:, :, 4] =
 3.03989e-17-1.46079e-17im  …  -1.748

# Visualize the coefficients for different N