In [ ]:
# setting the N value

N = 4;

# points in t direction
# trigpts returns N equally spaced points on an interval -1 to 1
# range is kind of like linspace! the length

t = pi* range(-1,1, length=N+1)[1:end-1];
t = reshape(t,:,1)


# chebpts returns chebyshev points of the second kind
# generates N+1 cheb pts in the interval [-1, 1], so includes endpoints
# points are clustered near the endpoints

r = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];
z = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];


# going from N-1 to 0 ensures that endpoints are included bc when you 
#plug in (N-1) and 0 into the formula, you get the endpoints included -1 and 1 regardless of N
# cosine part is just a formula for cheb pts of second kind

display(t)
display(z)
display(r)

4×1 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 4, 1) with eltype Float64:
 -3.141592653589793
 -1.5707963267948966
  0.0
  1.5707963267948966

4-element Vector{Float64}:
 -1.0
 -0.4999999999999998
  0.5000000000000001
  1.0

4-element Vector{Float64}:
 -1.0
 -0.4999999999999998
  0.5000000000000001
  1.0

In [2]:
# now to make the grid! this was a bit incorrect because we need the different layers? 
#I found a package that works better!

# tt = 
rr = hcat([r for _ in 1:N]...)
zz = vcat([transpose(z) for _ in 1:N]...)
 
display(rr)
display(zz)

4×4 Matrix{Float64}:
 -1.0  -1.0  -1.0  -1.0
 -0.5  -0.5  -0.5  -0.5
  0.5   0.5   0.5   0.5
  1.0   1.0   1.0   1.0

4×4 Matrix{Float64}:
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0

In [3]:
# same row vector vertical stacked
rr = [ri for ri in r, zi in z, ti in t]

# same column vector horizontal stacked
zz = [zi for ri in r, zi in z, ti in t]

# every entry in a matrix the same, but each layer has different value
tt = [ti for ri in r, zi in z, ti in t]

display(rr)
display(zz)
display(tt)


4×4×4×1 Array{Float64, 4}:
[:, :, 1, 1] =
 -1.0  -1.0  -1.0  -1.0
 -0.5  -0.5  -0.5  -0.5
  0.5   0.5   0.5   0.5
  1.0   1.0   1.0   1.0

[:, :, 2, 1] =
 -1.0  -1.0  -1.0  -1.0
 -0.5  -0.5  -0.5  -0.5
  0.5   0.5   0.5   0.5
  1.0   1.0   1.0   1.0

[:, :, 3, 1] =
 -1.0  -1.0  -1.0  -1.0
 -0.5  -0.5  -0.5  -0.5
  0.5   0.5   0.5   0.5
  1.0   1.0   1.0   1.0

[:, :, 4, 1] =
 -1.0  -1.0  -1.0  -1.0
 -0.5  -0.5  -0.5  -0.5
  0.5   0.5   0.5   0.5
  1.0   1.0   1.0   1.0

4×4×4×1 Array{Float64, 4}:
[:, :, 1, 1] =
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0

[:, :, 2, 1] =
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0

[:, :, 3, 1] =
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0

[:, :, 4, 1] =
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0
 -1.0  -0.5  0.5  1.0

4×4×4×1 Array{Float64, 4}:
[:, :, 1, 1] =
 -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159

[:, :, 2, 1] =
 -1.5708  -1.5708  -1.5708  -1.5708
 -1.5708  -1.5708  -1.5708  -1.5708
 -1.5708  -1.5708  -1.5708  -1.5708
 -1.5708  -1.5708  -1.5708  -1.5708

[:, :, 3, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 4, 1] =
 1.5708  1.5708  1.5708  1.5708
 1.5708  1.5708  1.5708  1.5708
 1.5708  1.5708  1.5708  1.5708
 1.5708  1.5708  1.5708  1.5708