# Imports

In [15]:
# import Pkg; Pkg.add("FFTW")
# import Pkg; Pkg.add("Plots")
# import Pkg; Pkg.add("MatrixEquations")
# using Pkg
# Pkg.add("SpecialFunctions")
# using Random
# using SpecialFunctions

#  This is the julia file with the functions! 

include("functions.jl")


pretty_print_4Darray_matlab_style (generic function with 1 method)

# Setting up r, t, and z points

In [ ]:
# setting the N value

N = 5;
T = 10;

# points in t direction
# trigpts returns N equally spaced points on an interval -1 to 1
# range is kind of like linspace!

t = pi* range(-1,1, length=N+1)[1:end-1];
t = reshape(t,:,1)


# chebpts returns chebyshev points of the second kind
# generates N+1 cheb pts in the interval [1, -1], so includes endpoints
# points are clustered near the endpoints

r = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];
z = [cos((pi*k)/(N-1)) for k in (N-1):-1:0];


# going from N-1 to 0 ensures that endpoints are included bc when you 
# plug in (N-1) and 0 into the formula, you get the endpoints included -1 and 1 regardless of N
# cosine part is just a formula for cheb pts of second kind

display(t)
display(z)
display(r)

5×1 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 5, 1) with eltype Float64:
 -3.141592653589793
 -1.8849555921538759
 -0.6283185307179586
  0.6283185307179586
  1.8849555921538759

5-element Vector{Float64}:
 -1.0
 -0.7071067811865475
  6.123233995736766e-17
  0.7071067811865476
  1.0

5-element Vector{Float64}:
 -1.0
 -0.7071067811865475
  6.123233995736766e-17
  0.7071067811865476
  1.0

# Setting up rr, tt, and zz Grids

In [5]:
# same row vector vertical stacked
rr = [ri for ri in r, zi in z, ti in t]

# same column vector horizontal stacked
zz = [zi for ri in r, zi in z, ti in t]

# every entry in a matrix the same, but each layer has different value
tt = [ti for ri in r, zi in z, ti in t]

rr = dropdims(rr; dims=4)
tt = dropdims(tt; dims=4)
zz = dropdims(zz; dims=4)

display(rr)
display(zz)
display(tt)

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

[:, :, 2] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0           1.0           1.0           1.0           1.0

[:, :, 3] =
 -1.0          -1.0          -1.0          -1.0          -1.0
 -0.707107     -0.707107     -0.707107     -0.707107     -0.707107
  6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17   6.12323e-17
  0.707107      0.707107      0.707107      0.707107      0.707107
  1.0          

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 2] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 3] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 4] =
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0
 -1.0  -0.707107  6.12323e-17  0.707107  1.0

[:, :, 5] =
 -1.0  -0.7

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159
 -3.14159  -3.14159  -3.14159  -3.14159  -3.14159

[:, :, 2] =
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496
 -1.88496  -1.88496  -1.88496  -1.88496  -1.88496

[:, :, 3] =
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319
 -0.628319  -0.628319  -0.628319  -0.628319  -0.628319

[:, :, 4] =
 0.628319  0.628319  0.628319  0.628319  0.628319
 0.628319  0.628319  0.628319  0.628319  0.628319
 0.628319  0.628319  0.628319  0.628319  0.628319

# Create Matrices

In [6]:
# get the matrices we want: C02, D2, A, coF
using LinearAlgebra, SparseArrays

# C01: Convert Chebyshev-T (T) coefficients to Chebyshev-U (U)
C01 = spdiagm(0 => 0.5*ones(N), 2 => -0.5*ones(N-2))
C01[1,1] = 1.0
println("C01:")
display(C01)
# C12: Convert Chebyshev-U to C^2, the continuous function space
K_1 = 1.0 ./ (1:N)
K_2 = 1.0 ./ (3:N)
C12 = spdiagm(0 => K_1, 2 => -K_2)
println("C12:")
display(C12)
# C02: Convert Chebyshev-T to C^2 (It's C01 * C12)
C02 = C01 * C12
println("C02:")
display(C02)

# D1: Differentiate Chebyshev-T and convert to Chebyshev-U
D1 = spdiagm(1 => 1:N-1)
println("D1: ")
display(D1)
# D2: Differentiate Chebyshev-T twice and convert to C²
D2 = spdiagm(2 => 2 .* (2:N-1))
println("D2: ")
display(D2)
# D0: Differentiate Chebyshev-T once
D0 = C01 \ D1
println("D0: ")
display(D0)

# R0: Multiply Cheb-T by x
R0 = spdiagm(-1 => 0.5*ones(N-1), 1 => 0.5*ones(N-1))
R0[2,1] = 1.0
println("R0:")
display(R0)
# R2: Multiply in C² space
denom = 4:2:2*N+2
K_sub  = ((1:N) ./ denom)[1:N-1]
K_super = ((3:N+2) ./ denom[1:N])[2:N]
R2 = spdiagm(-1 => K_sub, 1 => K_super)
println("R2:")
display(R2)
# R1: Multiply in Cheb-U basis
R1 = C12 \ R2 * C12
println("R1:")
display(R1)

# A: Laplacian operator
A = R2 * R2 * D2 + R2 * C12 * D1
println("A:")
display(A)

# coF: Laplacian multiplier
coF = R2 * R2 * C02
println("coF:")
display(coF)

C01:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 1.0   ⋅   -0.5    ⋅     ⋅ 
  ⋅   0.5    ⋅   -0.5    ⋅ 
  ⋅    ⋅    0.5    ⋅   -0.5
  ⋅    ⋅     ⋅    0.5    ⋅ 
  ⋅    ⋅     ⋅     ⋅    0.5

C12:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 1.0   ⋅   -0.333333    ⋅      ⋅ 
  ⋅   0.5    ⋅        -0.25    ⋅ 
  ⋅    ⋅    0.333333    ⋅    -0.2
  ⋅    ⋅     ⋅         0.25    ⋅ 
  ⋅    ⋅     ⋅          ⋅     0.2

C02:


5×5 SparseMatrixCSC{Float64, Int64} with 9 stored entries:
 1.0   ⋅    -0.5         ⋅      0.1
  ⋅   0.25    ⋅        -0.25     ⋅ 
  ⋅    ⋅     0.166667    ⋅     -0.2
  ⋅    ⋅      ⋅         0.125    ⋅ 
  ⋅    ⋅      ⋅          ⋅      0.1

D1: 


5×5 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  2  ⋅  ⋅
 ⋅  ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  ⋅  4
 ⋅  ⋅  ⋅  ⋅  ⋅

D2: 


5×5 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  ⋅  4  ⋅  ⋅
 ⋅  ⋅  ⋅  6  ⋅
 ⋅  ⋅  ⋅  ⋅  8
 ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅

D0: 


5×5 Matrix{Float64}:
 0.0  1.0  0.0  3.0  0.0
 0.0  0.0  4.0  0.0  8.0
 0.0  0.0  0.0  6.0  0.0
 0.0  0.0  0.0  0.0  8.0
 0.0  0.0  0.0  0.0  0.0

R0:

5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅   0.5   ⋅    ⋅    ⋅ 
 1.0   ⋅   0.5   ⋅    ⋅ 
  ⋅   0.5   ⋅   0.5   ⋅ 
  ⋅    ⋅   0.5   ⋅   0.5
  ⋅    ⋅    ⋅   0.5   ⋅ 


R2:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅    0.666667   ⋅      ⋅    ⋅ 
 0.25   ⋅        0.625   ⋅    ⋅ 
  ⋅    0.333333   ⋅     0.6   ⋅ 
  ⋅     ⋅        0.375   ⋅   0.583333
  ⋅     ⋅         ⋅     0.4   ⋅ 

R1:


5×5 Matrix{Float64}:
 0.0  0.5  0.0  0.0   0.0
 0.5  0.0  0.5  0.0  -0.166667
 0.0  0.5  0.0  0.5   0.0
 0.0  0.0  0.5  0.0   0.166667
 0.0  0.0  0.0  0.5   0.0

A:


5×5 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅    ⋅    1.33333    ⋅     2.66667
  ⋅   0.25   ⋅        2.625   ⋅ 
  ⋅    ⋅    0.666667   ⋅     3.73333
  ⋅    ⋅     ⋅        1.125   ⋅ 
  ⋅    ⋅     ⋅         ⋅     1.6

coF:


5×5 SparseMatrixCSC{Float64, Int64} with 12 stored entries:
 0.166667    ⋅       -0.0138889    ⋅         -0.0666667
  ⋅         0.09375    ⋅         -0.046875     ⋅ 
 0.0833333   ⋅        0.0305556    ⋅         -0.0433333
  ⋅         0.03125    ⋅          0.0260417    ⋅ 
  ⋅          ⋅        0.025        ⋅         -0.00666667

# Set Initial Condition

In [7]:
# finit(r, z, θ, t) = r .* sin.(θ) .+ z .* cos.(θ) # (This was a test function)

using SpecialFunctions

w54 = 18.98013387517992112;  # 4th root of the J-Bessel function of order 5
w33 = 13.0152007216984344;   # 3rd root of the J-Bessel function of order 5
q1 = 3;                      # Oscillation in z.
q2 = 2;   

u(r, z, th, t) = 10*exp(-((pi*q1)^2 + w33^2)*t) .* sin.(q1*pi*z) .* besselj.(3, w33 .* r) .* sin.(3*th) .+ exp(-((pi*q2)^2 + w54^2)*t) .* sin.(q2*pi*z) .* besselj.(5, w54 .* r) .* cos.(5*th);
finit(r,z,th,t) = u(r,z,th,0);

CFS = zeros(size(rr))

# Evaluate initial condition on the full (r, z, θ) grid
for j in 1:N
    CFS[:, j, :] .= finit(rr[:,j,:], zz[:,j,:], tt[:,j,:], 0)
end

display(CFS);

5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -4.4188e-32   -1.73899e-16  -6.94104e-32   1.73899e-16   4.4188e-32
  4.65351e-17   0.183136      7.30972e-17  -0.183136     -4.65351e-17
  1.42337e-77   1.44113e-62  -2.23583e-77  -1.44113e-62  -1.42337e-77
 -4.65351e-17  -0.183136     -7.30972e-17   0.183136      4.65351e-17
  4.4188e-32    1.73899e-16   6.94104e-32  -1.73899e-16  -4.4188e-32

[:, :, 2] =
 -1.04126e-31  -2.34585e-16   2.47398e-32   2.34585e-16   1.04126e-31
 -2.48636e-16  -0.115718      5.36751e-16   0.115718      2.48636e-16
 -2.27722e-62  -2.30563e-47   3.57705e-62   2.30563e-47   2.27722e-62
  2.48636e-16   0.115718     -5.36751e-16  -0.115718     -2.48636e-16
  1.04126e-31   2.34585e-16  -2.47398e-32  -2.34585e-16  -1.04126e-31

[:, :, 3] =
  5.27934e-32  -7.57074e-17  -2.21748e-31   7.57074e-17  -5.27934e-32
  5.24132e-16   0.666691     -6.7711e-16   -0.666691     -5.24132e-16
  3.68462e-62   3.73059e-47  -5.78778e-62  -3.73059e-47  -3.68462e-62
 -5.24132e-16  -0.666691     

# First 4 time steps

In [ ]:
CFS_func = V2C_cyl(CFS, "rzt")
println("CFS now: ")
pretty_print_3Darray_matlab_style(CFS_func)

alph = 1e-9

CFS_4D = complex(zeros(Float64, size(CFS_func)..., T))  # Create a new 4D array full of zeros of size (5,5,5,5)
CFS_4D[:,:,:,1] = CFS_func # copy over CFS_func into the first 4th slice


Hist = Vector{Array{Float64,3}}(undef, 3)  # Equivalent to cell(3,1)

# Plug in exact solution for the first four time steps
for j in 1:3
    Hist[j] = Array{Float64,3}(undef, size(rr))  # Allocate space for each time slice
    for k in 1:size(rr, 2)  # Assuming k indexes the 2nd dimension
        Hist[j][:,k,:] = finit(rr[:,k,:], zz[:,k,:], tt[:,k,:], j * alph)
    end
    CFS_4D[:,:,:,j+1] = V2C_cyl(Hist[j], "rzt")
end

pretty_print_4Darray_matlab_style(CFS_4D)

CFS now: 

(:,:, 1) =

 -0.0000  -0.0000i    0.0000 +  0.0000i    0.0000  -0.0000i    0.0000  -0.0000i   -0.0000 +  0.0000i  
 -0.0000  -0.0000i    0.0000  -0.1271i   -0.0000 +  0.0000i   -0.0000 +  0.1271i    0.0000 +  0.0000i  
  0.0000  -0.0000i    0.0000  -0.0000i   -0.0000 +  0.0000i   -0.0000 +  0.0000i   -0.0000 +  0.0000i  
 -0.0000 +  0.0000i   -0.0000 +  0.1271i    0.0000  -0.0000i    0.0000  -0.1271i    0.0000  -0.0000i  
  0.0000 +  0.0000i   -0.0000  -0.0000i   -0.0000 +  0.0000i   -0.0000 +  0.0000i    0.0000  -0.0000i  

(:,:, 2) =

   1.0e-17 *

  0.0000 +  0.1008i    0.0000 +  0.1346i   -0.0000  -0.0000i   -0.0000  -0.1346i    0.0000  -0.1008i  
  0.0908  -0.3289i   -2.8411 +  1.8832i    0.0000  -0.0000i    1.9429  -2.2636i   -0.0908 +  0.3289i  
 -0.0000 +  0.0000i   -0.0000 +  0.0000i    0.0000  -0.0000i    0.0000  -0.0000i    0.0000  -0.0000i  
 -0.2031 +  0.2473i    1.6653  -1.9376i   -0.0000 +  0.0000i   -1.9757 +  1.2621i    0.2031  -0.2473i  
 -0.0000  -0.1008i 

# Full time step

In [17]:
q = (12/25)*alph

for d = 5:T
    RHS = (48/25)*CFS_4D[:,:,:,d-1]-(36/25)*CFS_4D[:,:,:,d-2]+(16/25)*CFS_4D[:,:,:,d-3]-(3/25)*CFS_4D[:,:,:,d-4]
    CFS_4D[:,:,:,d] = Heat3DSolver(RHS,q,N,C02,A,D2,coF)
end

pretty_print_4Darray_matlab_style(CFS_4D)


(:,:,1,1) =

 -0.0000  -0.0000i    0.0000 +  0.0000i    0.0000  -0.0000i    0.0000  -0.0000i   -0.0000 +  0.0000i  
 -0.0000  -0.0000i    0.0000  -0.1271i   -0.0000 +  0.0000i   -0.0000 +  0.1271i    0.0000 +  0.0000i  
  0.0000  -0.0000i    0.0000  -0.0000i   -0.0000 +  0.0000i   -0.0000 +  0.0000i   -0.0000 +  0.0000i  
 -0.0000 +  0.0000i   -0.0000 +  0.1271i    0.0000  -0.0000i    0.0000  -0.1271i    0.0000  -0.0000i  
  0.0000 +  0.0000i   -0.0000  -0.0000i   -0.0000 +  0.0000i   -0.0000 +  0.0000i    0.0000  -0.0000i  

(:,:,2,1) =

   1.0e-17 *

  0.0000 +  0.1008i    0.0000 +  0.1346i   -0.0000  -0.0000i   -0.0000  -0.1346i    0.0000  -0.1008i  
  0.0908  -0.3289i   -2.8411 +  1.8832i    0.0000  -0.0000i    1.9429  -2.2636i   -0.0908 +  0.3289i  
 -0.0000 +  0.0000i   -0.0000 +  0.0000i    0.0000  -0.0000i    0.0000  -0.0000i    0.0000  -0.0000i  
 -0.2031 +  0.2473i    1.6653  -1.9376i   -0.0000 +  0.0000i   -1.9757 +  1.2621i    0.2031  -0.2473i  
 -0.0000  -0.1008i   -0.000

# Running C2V_cyl

In [18]:
CFS_4D[:,:,:,T] = C2V_cyl(CFS_4D[:,:,:,T],"rzt");
pretty_print_4Darray_matlab_style(CFS_4D);

(5,)
COEFFS: 
ComplexF64[-1.598729021709746e-32 - 2.6796435445085847e-16im, 3.2711737374943766e-19 - 5.120084279946503e-15im, 1.0795639380065704e-39 + 8.756992107695187e-24im, -3.2711737374943766e-19 + 5.120084279946503e-15im, 1.5987288057969583e-32 + 2.6796433693687423e-16im]
(5,)
COEFFS: 
ComplexF64[5.5025135577364e-33 + 1.0234863024934017e-16im, 8.095386684230643e-18 - 0.06355504763634229im, -3.485698453820187e-40 - 7.047395226613767e-24im, -8.095386684230643e-18 + 0.06355504763634229im, -5.502512860596709e-33 - 1.0234861615454972e-16im]
(5,)
COEFFS: 
ComplexF64[3.4578382201404995e-32 + 1.729030754200971e-18im, -2.1107144477577834e-21 + 4.4551985277459126e-15im, -8.802744500167225e-40 + 8.492108377340043e-25im, 2.1107144477577834e-21 - 4.4551985277459126e-15im, -3.45783804408561e-32 - 1.7290324526226464e-18im]
(5,)
COEFFS: 
ComplexF64[-5.5025135577364e-33 - 1.0234863024934017e-16im, -8.095386684230643e-18 + 0.06355504763634229im, 3.485698453820187e-40 + 7.047395226613767e-24im, 8.09